version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: jk_mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jk_backend
      MYSQL_USER: jk_user
      MYSQL_PASSWORD: jk_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
